# See https://pre-commit.com for more information
default_language_version:
  # default language version for each language used in the repository
  python: python3.9
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      # See https://pre-commit.com/hooks.html for more hooks
      - id: check-ast
      - id: check-case-conflict
      #      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: debug-statements
      - id: end-of-file-fixer
      - id: name-tests-test
        args: [ "--django" ]
      - id: trailing-whitespace
  - repo: https://github.com/asottile/seed-isort-config
    rev: v2.2.0
    hooks:
      - id: seed-isort-config
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.10.0
    hooks:
      - id: pyupgrade
        args: [ "--py36-plus", "--py37-plus", "--py38-plus", "--py39-plus" ]
  - repo: https://github.com/pycqa/isort
    rev: 5.7.0
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
  - repo: https://github.com/pycqa/bandit
    rev: 1.7.0
    hooks:
      - id: bandit
        args: [ "-iii", "-ll" ]
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
      - id: flake8
        additional_dependencies: [
            "flake8-bugbear",
            "flake8-comprehensions",
            "flake8-mutable",
            "flake8-print",
            "flake8-simplify",
        ]
  - repo: https://github.com/pycqa/pylint
    rev: "pylint-2.7.2"
    hooks:
      - id: pylint
        exclude: "[a-zA-Z]*/(migrations)/(.)*"
        args: [ "--load-plugins=pylint_django", "--django-settings-module=config.settings" ]
        additional_dependencies: [
          # pylint dependency
            pylint_django==2.4.2,
          # runtime dependencies
            asgiref==3.3.1,
            certifi==2020.12.5,
            cffi==1.14.4,
            chardet==4.0.0,
            coreapi==2.3.3,
            coreschema==0.0.4,
            cryptography==3.3.1,
            django-debug-toolbar==3.2,
            Django==3.1.5,
            django-cors-headers==3.6.0,
            django-rest-knox==4.1.0,
            djangorestframework==3.12.2,
            drf-yasg==1.20.0,
            gunicorn==20.0.4,
            idna==2.10,
            inflection==0.5.1,
            itypes==1.2.0,
            Jinja2==2.11.2,
            MarkupSafe==1.1.1,
            openapi-codec==1.3.2,
            packaging==20.8,
            pre-commit==2.11.1,
            psycopg2-binary==2.8.6,
            pycparser==2.20,
            pyparsing==2.4.7,
            pytz==2020.5,
            PyYAML==5.3.1,
            requests==2.25.1,
            ruamel.yaml==0.16.12,
            ruamel.yaml.clib==0.2.2,
            simplejson==3.17.2,
            six==1.15.0,
            sqlparse==0.4.1,
            uritemplate==3.0.1,
            urllib3==1.26.2,
            whitenoise==5.2.0,

        ]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.812'
    hooks:
      - id: mypy
        exclude: "[a-zA-Z]*/(migrations)/(.)*"
        additional_dependencies: [
          # mypy dependencies
            djangorestframework-stubs,
            django-stubs,
          # runtime dependencies
            asgiref==3.3.1,
            certifi==2020.12.5,
            cffi==1.14.4,
            chardet==4.0.0,
            coreapi==2.3.3,
            coreschema==0.0.4,
            cryptography==3.3.1,
            django-debug-toolbar==3.2,
            Django==3.1.5,
            django-cors-headers==3.6.0,
            django-rest-knox==4.1.0,
            djangorestframework==3.12.2,
            drf-yasg==1.20.0,
            gunicorn==20.0.4,
            idna==2.10,
            inflection==0.5.1,
            itypes==1.2.0,
            Jinja2==2.11.2,
            MarkupSafe==1.1.1,
            openapi-codec==1.3.2,
            packaging==20.8,
            pre-commit==2.11.1,
            psycopg2-binary==2.8.6,
            pycparser==2.20,
            pyparsing==2.4.7,
            pytz==2020.5,
            PyYAML==5.3.1,
            requests==2.25.1,
            ruamel.yaml==0.16.12,
            ruamel.yaml.clib==0.2.2,
            simplejson==3.17.2,
            six==1.15.0,
            sqlparse==0.4.1,
            uritemplate==3.0.1,
            urllib3==1.26.2,
            whitenoise==5.2.0,

        ]
